# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
# The configuration file defines the components and policies that your model will use to make predictions based on user input.
recipe: default.v1
language: zh

# wait 配置BERT语言模型的组件的方案
# todo 配置语言模型需要的分词器 - jieba分词;这个分词器会和MITIE语言模型要求的词表有冲突
#pipeline_cp:
#  - name: JiebaTokenizer
#    dictionary_path: /mnt/f/mprtModel/mitie_model_and_vocab/dict.chn.txt.big.txt
#    "intent_tokenization_flag": False
#    "intent_split_symbol": "_"
#    "token_pattern": None


pipeline:
#  - name: MitieNLP
#    #    model: /mnt/f/mprtModel/mitie_model_and_vocab/total_word_feature_extractor_zh.dat # linux
#    model: F:\mprtModel\mitie_model_and_vocab\total_word_feature_extractor_zh.dat # windows
#  - name: JiebaTokenizer
#    #    dictionary_path: /mnt/f/mprtModel/mitie_model_and_vocab/dict.chn.txt.big.txt # linux
#    dictionary_path: F:\mprtModel\mitie_model_and_vocab\dict.chn.txt.big.txt # windows
#  - name: MitieFeaturizer
#    pooling: mean
#  - name: MitieIntentClassifier
#  - name: MitieEntityExtractor
  - name: SpacyNLP
    model: zh_core_web_lg
    case_sensitive: False  # 表示 hello 和 Hello 相同意思
  - name: SpacyTokenizer
    token_pattern: None
  - name: SpacyFeaturizer
    pooling: mean
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: SpacyEntityExtractor
    dimensions: ["goods","code","name","city","part","street"]
  - name: RegexFeaturizer
    case_sensitive: False
    use_word_boundaries: False # 配置了 lookup table 时使用
  - name: RegexEntityExtractor
    case_sensitive: False # 大小写不敏感
    use_lookup_tables: False
    use_regexes: True
    use_word_boundaries: False # 配置了 lookup table 时使用

# Configuration for Rasa Core: https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.5  # 以下规则将要求用户在发送低置信度的消息时重新组织句子
    core_fallback_action_name: action_default_fallback  # 对于next action的预测处于低置信度的情况要采用的默认的action去对任意一种intent做出回答
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
